### ISSUE TITLE
Seeder job incompatible with ArgoCD

### ISSUE THREAD

**Issue by djerfy** [opf/helm-charts#30]
Hi,

I've a problem with the seeder job due to the random name:

https://github.com/opf/helm-charts/blob/d5292d681ce7dec7b517de5c669f5ce11c37c86d/charts/openproject/templates/seeder-job.yaml#L4

And in ArgoCD my application is always OutOfSync. Also the seeder job doesn't support annotation.
This random name is mandatory?

Else can you implement `seeder.annotations: {}` option?

Thanks

**Comment by machisuji** [comment]
Hi @djerfy,

we have the dynamic name so that a new seeder job is run with every deployment.
This is to make sure that the database has the correct schema and the latest seed data is installed.

I have found other ways of achieving this using hooks but found the solution a lot more complicated so I've opted for the simple solution. I'm open to suggestions, though.

In the meantime @oliverguenther was so kind as to add annotations for the seeder job as you suggested.

**Comment by djerfy** [comment]
> Hi @djerfy,
> 
> we have the dynamic name so that a new seeder job is run with every deployment. This is to make sure that the database has the correct schema and the latest seed data is installed.
> 
> I have found other ways of achieving this using hooks but found the solution a lot more complicated so I've opted for the simple solution. I'm open to suggestions, though.
> 
> In the meantime @oliverguenther was so kind as to add annotations for the seeder job as you suggested.

Hi @machisuji,

Thank you for changes, good for me 👍 

My configuration in ArgoCD:

```yaml
seederJob:
    annotations:
        argocd.argoproj.io/hook: PreSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
```
